---
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - config:/data/configdb

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

volumes:
  data:
  config:
